/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import model.validations.UserDataValidations;

import java.io.FileNotFoundException;
import ficheros.ClassFichero;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.exceptions.InvalidDateException;
import model.exceptions.InvalidNifException;

/**
 *
 * @author ruthagulop
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        initConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabelTitle = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        JTextFieldName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        JTextFieldNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        JTextFieldEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        ErrorName = new javax.swing.JLabel();
        JTextFieldZipCode = new javax.swing.JLabel();
        jTextFieldZipCode = new javax.swing.JTextField();
        JTextFieldBirthdate = new javax.swing.JLabel();
        jTextFieldBirthdate = new javax.swing.JTextField();
        JTextFieldAge = new javax.swing.JLabel();
        jButtonValidate = new javax.swing.JButton();
        ErrorNif = new javax.swing.JLabel();
        ErrorEmail = new javax.swing.JLabel();
        ErrorBirthdate = new javax.swing.JLabel();
        ErrorZip = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jLabelAge = new javax.swing.JLabel();
        jButtonCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        JLabelTitle.setBackground(new java.awt.Color(0, 51, 153));
        JLabelTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLabelTitle.setText("VALIDADOR DATOS USUARIO");

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gui/Diseño sin título 1.png"))); // NOI18N
        jLabelIcon.setPreferredSize(new java.awt.Dimension(200, 100));

        JTextFieldName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTextFieldName.setText("Name: ");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        JTextFieldNIF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTextFieldNIF.setText("NIF: ");

        JTextFieldEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTextFieldEmail.setText("Email: ");

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        ErrorName.setForeground(new java.awt.Color(204, 0, 0));

        JTextFieldZipCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTextFieldZipCode.setText("ZipCode: ");

        jTextFieldZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZipCodeActionPerformed(evt);
            }
        });

        JTextFieldBirthdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTextFieldBirthdate.setText("Birthdate:");

        jTextFieldBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdateActionPerformed(evt);
            }
        });

        JTextFieldAge.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTextFieldAge.setText("Age:");

        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        ErrorNif.setBackground(new java.awt.Color(255, 255, 255));
        ErrorNif.setForeground(new java.awt.Color(204, 0, 0));

        ErrorEmail.setBackground(new java.awt.Color(255, 255, 255));
        ErrorEmail.setForeground(new java.awt.Color(153, 0, 0));

        ErrorBirthdate.setBackground(new java.awt.Color(153, 0, 0));

        ErrorZip.setBackground(new java.awt.Color(255, 255, 255));
        ErrorZip.setForeground(new java.awt.Color(153, 0, 0));

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonValidate)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTextFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButtonClear)
                                .addGap(94, 94, 94)
                                .addComponent(jButtonCSV))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNIF, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jTextFieldName)
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jTextFieldZipCode)
                                    .addComponent(jTextFieldBirthdate))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(ErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ErrorNif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ErrorBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addGap(16, 16, 16))
                                            .addComponent(ErrorZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelTitle))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldName)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldNIF)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ErrorNif)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldEmail)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ErrorEmail)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFieldBirthdate)
                    .addComponent(jTextFieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorBirthdate))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldAge)
                    .addComponent(jLabelAge))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldZipCode)
                    .addComponent(jTextFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorZip))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidate)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCSV))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        JTextFieldBirthdate.getAccessibleContext().setAccessibleName("Birthdate");
        JTextFieldAge.getAccessibleContext().setAccessibleName("Age: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initConfig() {
        jButtonCSV.setEnabled(false); // 
        jButtonValidate.setEnabled(true);
        jButtonClear.setEnabled(true);

        // Limpiar los campos de texto
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthdate.setText("");
        jLabelAge.setText("");
        jTextFieldZipCode.setText("");

        // Limpiar los mensajes de error
        ErrorName.setText("");
        ErrorNif.setText("");
        ErrorEmail.setText("");
        ErrorBirthdate.setText("");
        ErrorZip.setText("");

        this.setLocationRelativeTo(null);
    }

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZipCodeActionPerformed

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        // TODO add your handling code here:
        boolean datosCorrectos = true;
        String name = jTextFieldName.getText();
        if (!UserDataValidations.isAlphabetic(name)) {
            ErrorName.setText("Incorrect name!");
            datosCorrectos = false;
        }

        String nif = jTextFieldNIF.getText();
        try {
            if (!UserDataValidations.checkId(nif)) {
                ErrorNif.setText("Incorrect NIF!");
                datosCorrectos = false;
            }
        } catch (InvalidNifException ex) {
           ErrorNif.setText(ex.getMessage());
           datosCorrectos = false;
        }

        String email = jTextFieldEmail.getText();
        if (!UserDataValidations.checkEmail(email)) {
            ErrorEmail.setText("Incorrect email");
            datosCorrectos = false;
        }
        String birthdate = jTextFieldBirthdate.getText();
        try {
            if (!UserDataValidations.checkDate(birthdate)) {
                ErrorBirthdate.setText("");
                datosCorrectos = false;
            } else {
                int edadInt = UserDataValidations.calculateAge(birthdate);
                String edad = String.valueOf(edadInt);
                jLabelAge.setText(edad);
            }
        } catch (InvalidDateException ex) {
           ErrorBirthdate.setText(ex.getMessage());
        }

        String zip = jTextFieldZipCode.getText();
        if (!UserDataValidations.checkZipCode(zip)) {
            ErrorZip.setText("Incorrect Zipcode");
            datosCorrectos = false;
        }
        if (datosCorrectos) {
            jTextFieldName.setEditable(false);
            jTextFieldNIF.setEditable(false);
            jTextFieldEmail.setEditable(false);
            jTextFieldBirthdate.setEditable(false);
            jTextFieldZipCode.setEditable(false);

            jButtonValidate.setEnabled(false);
            jButtonCSV.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthdate.setText("");
        jLabelAge.setText("");
        jTextFieldZipCode.setText("");

        ErrorName.setText("");
        ErrorNif.setText("");
        ErrorEmail.setText("");
        ErrorBirthdate.setText("");
        ErrorZip.setText("");
        
        jTextFieldName.setEditable(true);
        jTextFieldNIF.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldBirthdate.setEditable(true);
        jTextFieldZipCode.setEditable(true);
        
        jButtonValidate.setEnabled(true);
        jButtonClear.setEnabled(true);
        jButtonCSV.setEnabled(false);
        
        

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        // TODO add your handling code here:
        //csv comma separated values
        /* String folderPath = "data";
        String filePath = folderPath + "/user_data.csv";

        java.io.File folder = new java.io.File(folderPath);
        if (!folder.exists()) {
            folder.mkdir();
        }

        java.io.File file = new java.io.File(filePath);
        boolean isNewFile = !file.exists() || file.length() == 0;

        try (FileWriter writer = new FileWriter(filePath, true)) {
            if (isNewFile) {
                writer.append("Name,NIF,Email,Birthdate,Age,ZipCode\n");
            }
            String name = jTextFieldName.getText();
            String nif = jTextFieldNIF.getText();
            String email = jTextFieldEmail.getText();
            String birthdate = jTextFieldBirthdate.getText();
            String age = jLabelAge.getText();
            String zipCode = jTextFieldZipCode.getText();
            
            writer.append(name).append(",")
                  .append(nif).append(",")
                  .append(email).append(",")
                  .append(birthdate).append(",")
                  .append(age).append(",")
                  .append(zipCode).append(",")
            
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this, "Error al crear el CSV: ");
        }*/
        String filePath = "user_data_RDALL.csv";
        java.io.File file = new java.io.File(filePath);
        boolean isNewFile = !file.exists() || file.length() == 0;
        
        
        String name = jTextFieldName.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String birthdate = jTextFieldBirthdate.getText();
        String age = jLabelAge.getText();
        String zipCode = jTextFieldZipCode.getText();
        
        String line = name + ";" + nif + ";" + email + ";" + birthdate + ";" + age + ";" + zipCode + ";"+ "\n";

        ClassFichero.writeFile(line);
        JOptionPane.showMessageDialog(this, "Usuario creado", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        
        jButtonCSV.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCSVActionPerformed

    private void jTextFieldBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        ClassFichero.createFile("user_data_RDALL.csv");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorBirthdate;
    private javax.swing.JLabel ErrorEmail;
    private javax.swing.JLabel ErrorName;
    private javax.swing.JLabel ErrorNif;
    private javax.swing.JLabel ErrorZip;
    private javax.swing.JLabel JLabelTitle;
    private javax.swing.JLabel JTextFieldAge;
    private javax.swing.JLabel JTextFieldBirthdate;
    private javax.swing.JLabel JTextFieldEmail;
    private javax.swing.JLabel JTextFieldNIF;
    private javax.swing.JLabel JTextFieldName;
    private javax.swing.JLabel JTextFieldZipCode;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBirthdate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldZipCode;
    // End of variables declaration//GEN-END:variables

}
